"""create users and user_metrics tables

Revision ID: 07b23fc3bbed
Revises: 
Create Date: 2025-08-29 03:19:44.811620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07b23fc3bbed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('last_weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Enum('LOSS_WEIGHT', 'GAIN_MUSCLE', 'MAINTAIN', name='goal'), nullable=False),
    sa.Column('experience', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='experience'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_date_desc', 'user_metrics', ['user_id', sa.literal_column('date DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_date_desc', table_name='user_metrics')
    op.drop_table('user_metrics')
    op.drop_table('users')
    # ### end Alembic commands ###
